### ISSUE TITLE
Where do I resume reading.

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [BerkomzxTL/Translations#1]
If we count from the last chapter translated by Human Translations (c215), where do I have to start reading from? From the start of v10 or do I have to read some chapters (and which) by Fans Translations, then start v10?

**Comment by BerkomzxTL** [comment]
> If we count from the last chapter translated by Human Translations (c215), where do I have to start reading from? From the start of v10 or do I have to read some chapters (and which) by Fans Translations, then start v10?

I added a note to the volume 10 readme, but here it is as well...

- Based on the actual wn, volume 9 technically ends on the release marked ["v9c208"](https://thecenttranslations.wordpress.com/2021/04/22/chapter-208-volume-9/)
- Volume 10 therefore begins on "v9c209"
- Also based on NovelUpdates, V10 has been completely translated (except for chapter 15, which I think was accidentally skipped), meaning that volume 10 ends on ["c252"](https://fanstranslations.com/novel/demon-noble-girl-story-of-a-careless-demon/chapter-252/)

Also... the actual web novel chapters do not align with how translators split the chapters up on NovelUpdates...

**Comment by l-l-l-l-l-l** [comment]
So it should be chapter 6. Thanks.
